version: '2.13.0'
services:
  mongodb:
    image: mongo
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
     - mongo-data:/data/db
     #<host-volume-name>:<path-inside-of-the-mongodb-container>
  mongo-express:
    image: mongo-express
    ports:
     - 8080:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
     - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
  docker-app:
    image: myappprivatecontainerregistry.azurecr.io/docker-app:private-v2
    ports:
     - 3000:3000    
volumes:
  mongo-data:
   driver: local # Provides additional information to Docker to create that physical storage on local file system